# Generated by Django 3.0.8 on 2020-08-02 03:46

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breed_or_coat', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('animal_name', models.CharField(max_length=40)),
                ('image', models.ImageField(default='images/default.png', upload_to='images/')),
                ('primary_color', colorfield.fields.ColorField(default='#FF0000', max_length=18)),
                ('secondary_color', colorfield.fields.ColorField(default='#FF0000', max_length=18)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=6)),
                ('species', models.CharField(max_length=40)),
                ('birth_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('weight', models.IntegerField()),
                ('height', models.IntegerField()),
                ('fixed', models.BooleanField()),
                ('description', models.TextField()),
                ('adopted', models.DateTimeField(blank=True, default=None, null=True)),
                ('house_trained', models.BooleanField()),
                ('micro_chipped', models.BooleanField(default=False)),
                ('currently_lost', models.BooleanField(default=False)),
                ('date_lost', models.DateTimeField(blank=True, default=None, null=True)),
                ('date_found', models.DateTimeField(blank=True, default=None, null=True)),
                ('was_euthanized', models.BooleanField(default=False)),
                ('date_euthanized', models.DateTimeField(blank=True, default=None, null=True)),
                ('reasons_euthanized', models.TextField(blank=True, default=None, null=True)),
                ('breed_or_coat', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='pets.Breed')),
                ('owner', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='pets.Human')),
            ],
        ),
    ]
