# Generated by Django 3.0.8 on 2020-07-31 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostpet',
            name='date_found',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
