# Generated by Django 3.0.8 on 2020-08-01 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_auto_20200730_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='Human',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='animal',
            name='adopted',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='euthanized',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='animal',
            name='micro_chipped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='animal',
            name='reason_euthanized',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
