# Generated by Django 3.0.8 on 2020-08-01 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0004_animal_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='age',
        ),
        migrations.AddField(
            model_name='animal',
            name='birth_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
