# Generated by Django 3.0.8 on 2020-08-01 02:12

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0005_auto_20200731_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='primary_color',
            field=colorfield.fields.ColorField(default=None, max_length=18),
        ),
        migrations.AddField(
            model_name='animal',
            name='secondary_color',
            field=colorfield.fields.ColorField(default=None, max_length=18),
        ),
    ]
