# Generated by Django 3.0.8 on 2020-08-01 02:13

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_auto_20200731_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='primary_color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
        migrations.AlterField(
            model_name='animal',
            name='secondary_color',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
    ]
